apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-shop
spec:
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
      - name: shop-service
        image: ngoctd/ecommerce-shop:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: shop-service
  ports:
  - port: 8080
    targetPort: 8080

