// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package repository

import (
	"database/sql"
	"time"
)

type Shop struct {
	ID        int64
	SellerID  int64
	Name      string
	Avatar    sql.NullString
	CreatedAt time.Time
}
