// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: shop_crud.sql

package repository

import (
	"context"
	"database/sql"
)

const createShop = `-- name: CreateShop :exec
INSERT INTO shop ("seller_id", "name", "avatar") VALUES ($1, $2, $3)
`

type CreateShopParams struct {
	SellerID int64
	Name     string
	Avatar   sql.NullString
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.ExecContext(ctx, createShop, arg.SellerID, arg.Name, arg.Avatar)
	return err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, seller_id, name, avatar, created_at FROM shop WHERE "id" = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id int64) (Shop, error) {
	row := q.db.QueryRowContext(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Avatar,
		&i.CreatedAt,
	)
	return i, err
}
