// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: shop_crud.sql

package repository

import (
	"context"
	"database/sql"
)

const createShop = `-- name: CreateShop :exec
INSERT INTO shop ("seller_id", "name", "avatar") VALUES ($1, $2, $3)
`

type CreateShopParams struct {
	SellerID int64
	Name     string
	Avatar   sql.NullString
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.ExecContext(ctx, createShop, arg.SellerID, arg.Name, arg.Avatar)
	return err
}
